name: 'testing-workflows'
on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: test code
        run: npm run test
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: building
        run: npm run build
      - name: Output build
        run: echo "Building/Deploying..."